version: '3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    ports:
      - "9001:5432"

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "9000:8080"
 

